In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [12]:
data = pd.read_csv('C:/Users/setso/Downloads/real_estate_price_size_year.csv')

In [13]:
data.head()

price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

In [14]:
data.describe()


price         size         year
count     100.000000   100.000000   100.000000
mean   292289.470160   853.024200  2012.600000
std     77051.727525   297.941951     4.729021
min    154282.128000   479.750000  2006.000000
25%    234280.148000   643.330000  2009.000000
50%    280590.716000   696.405000  2015.000000
75%    335723.696000  1029.322500  2018.000000
max    500681.128000  1842.510000  2018.000000

In [16]:
x = data[['size','year']]
y = data['price']

In [17]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(x)
x_scaled = scaler.transform(x)

In [18]:
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression()

In [19]:
reg.intercept_

292289.4701599997

In [20]:
reg.coef_

array([67501.57614152, 13724.39708231])

In [21]:
reg.score(x_scaled,y)

0.7764803683276793

In [23]:
def adj_r2(x,y):
    r2 = reg.score(x,y)
    n = x.shape[0]
    p = x.shape[1]
    adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
    return adjusted_r2

In [24]:
adj_r2(x_scaled,y)

0.77187171612825

In [25]:
new_data =[[750, 2009]]
new_data_scaled = scaler.transform(new_data)

C:\Users\setso\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [26]:
reg.predict(new_data_scaled)

array([258330.34465995])

In [27]:
from sklearn.feature_selection import f_regression

In [29]:
f_regression(x_scaled, y)

(array([285.92105192,   0.85525799]), array([8.12763222e-31, 3.57340758e-01]))

In [30]:
p_values = f_regression(x,y)[1]
p_values.round(3)

array([0.   , 0.357])

In [31]:
reg_summary = pd.DataFrame(data = x.columns.values, columns=['Features'])
reg_summary ['Coefficients'] = reg.coef_
reg_summary ['p-values'] = p_values.round(3)
reg_summary

Features  Coefficients  p-values
0     size  67501.576142     0.000
1     year  13724.397082     0.357